version: '3.3'

services:
    db:
        image: postgres:12
        restart: unless-stopped
        volumes:
            - pgData:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker

    web:
        build:
          context: .
          dockerfile: Dockerfile
        command: ./docker-entrypoint.sh
        env_file:
          - ./.env
        depends_on:
          - db
        ports:
          - 4400:8000
        restart: always
        stdin_open: true
        tty: true
        volumes:
          - .:/app:rw
        working_dir: /app

volumes:
    pgData:
