# Generated by Django 4.1.3 on 2022-11-29 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('podcast', models.URLField(max_length=255)),
                ('vodcast', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shiur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('audio_src', models.URLField()),
                ('video_src', models.URLField(null=True)),
                ('track', models.PositiveIntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shiurim', to='api.series')),
            ],
        ),
    ]
