# Generated by Django 4.1.3 on 2022-12-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_options_alter_series_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='podcast',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='vodcast',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
