# Generated by Django 4.1.3 on 2022-12-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_series_podcast_alter_series_vodcast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiur',
            options={'ordering': ('track',), 'verbose_name_plural': 'Shiurim'},
        ),
        migrations.AlterField(
            model_name='shiur',
            name='size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shiur',
            name='track',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
