# Generated by Django 4.1.3 on 2022-12-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_created_at_alter_category_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiur',
            name='imported_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.series'),
        ),
        migrations.AddField(
            model_name='shiur',
            name='imported_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
