# Generated by Django 4.1.3 on 2022-12-14 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_shiur_created_at_alter_shiur_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='shiur',
            name='categories',
            field=models.ManyToManyField(null=True, to='api.category'),
        ),
        migrations.AddField(
            model_name='shiur',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.speaker'),
        ),
    ]
