# Generated by Django 4.1.3 on 2022-12-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_speaker_shiur_categories_shiur_speaker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiur',
            options={'ordering': ['position', 'created_at'], 'verbose_name_plural': 'Shiurim'},
        ),
        migrations.RenameField(
            model_name='shiur',
            old_name='track',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='shiur',
            name='categories',
            field=models.ManyToManyField(to='api.category'),
        ),
    ]
